/**
 * A `node` for DSH subprocesses, provided by this Electron executable.
 *
 * DSH starts some child programs with `process.execPath` as if it were Node —
 * notably `dsh-ptc-runtime-node`, which runs every Node PTC program that way.
 * Inside Electron `process.execPath` is the Electron app itself, so the child
 * boots as a second Electron *app* and treats the script as an app directory.
 * `ELECTRON_RUN_AS_NODE=1` would make it Node, but it cannot be exported from
 * the main process: every Chromium helper would inherit it and die, and the
 * PTC runtime strips it from the child environment anyway.
 *
 * The fix is scoped to the one place that needs it: a tiny shell shim that
 * sets the flag and `exec`s this executable, handed to the `ptc-runtime` row as
 * its `nodeExecutable` through a generated `--patch` overlay. Nothing else in
 * the tree sees the variable.
 *
 * Both files live in userData and are rewritten on every launch, because the
 * executable path changes whenever the app bundle moves.
 */

import { chmodSync, mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Directory inside userData holding generated runtime files. */
const RUNTIME_DIRECTORY = 'runtime';

/**
 * Quote a value for a POSIX shell single-quoted string.
 * @param value - raw text.
 * @returns the quoted form.
 */
export function shellQuote(value) {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * Text of the shim script.
 * @param executable - Electron executable to run as Node.
 * @returns the script.
 */
export function shimScript(executable) {
  return [
    '#!/bin/sh',
    '# Generated by dsh-desktop on every launch; see src/main/node-shim.js.',
    `ELECTRON_RUN_AS_NODE=1 exec ${shellQuote(executable)} "$@"`,
    '',
  ].join('\n');
}

/**
 * Text of the overlay that points `ptc-runtime` at the shim.
 *
 * A patch replaces a row's whole config. The shipped `ptc-runtime` row has
 * none, so this states only `nodeExecutable` and every other key keeps its
 * schema default.
 *
 * @param shim - absolute path of the shim.
 * @returns YAML text.
 */
export function overlayYaml(shim) {
  return [
    '# Generated by dsh-desktop on every launch; see src/main/node-shim.js.',
    '- id: ptc-runtime',
    '  config:',
    `    nodeExecutable: ${JSON.stringify(shim)}`,
    '',
  ].join('\n');
}

/**
 * Write the shim and its overlay.
 *
 * @param options - `{ userData, executable }`.
 * @returns `{ shim, overlay }` absolute paths.
 */
export function installNodeShim(options) {
  const directory = join(options.userData, RUNTIME_DIRECTORY);
  mkdirSync(directory, { recursive: true });
  const shim = join(directory, 'node');
  const overlay = join(directory, 'node-shim.patch.yml');
  writeAtomic(shim, shimScript(options.executable), 0o755);
  writeAtomic(overlay, overlayYaml(shim), 0o644);
  return { shim, overlay };
}

/**
 * Replace a file atomically, so a concurrent reader never sees half a script.
 * @param path - target.
 * @param text - content.
 * @param mode - permission bits.
 */
function writeAtomic(path, text, mode) {
  const temporary = `${path}.${String(process.pid)}.tmp`;
  writeFileSync(temporary, text, { mode });
  chmodSync(temporary, mode);
  renameSync(temporary, path);
}
